# Generated by Django 4.2.1 on 2023-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options_alter_rubric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('b', 'Kуплю'), ('s', 'Продам'), ('c', 'Обменяю')], default='s', max_length=1),
        ),
    ]
