# Generated by Django 4.2.1 on 2023-06-23 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('viewed', 'Просмотренно'), ('in queue', 'В очереди'), ('rejected', 'Отказанно')], default=None, max_length=13, verbose_name='Статус заявки')),
                ('fname', models.CharField(max_length=33, validators=[django.core.validators.MinValueValidator(2, message='Минимум 2 символа')], verbose_name='Фамилия')),
                ('sname', models.CharField(max_length=33, validators=[django.core.validators.MinValueValidator(2, message='Минимум 2 символа')], verbose_name='Имя')),
                ('umail', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите действительный адрес')], verbose_name='Электронная почта')),
            ],
        ),
    ]
