# Generated by Django 4.2.1 on 2023-06-23 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_req',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='user_req',
            name='fname',
            field=models.CharField(max_length=33, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user_req',
            name='sname',
            field=models.CharField(max_length=33, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Имя'),
        ),
    ]
