# Generated by Django 4.2.1 on 2023-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appS', '0002_alter_user_req_options_alter_user_req_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_req',
            name='status',
            field=models.CharField(choices=[('viewed', 'Просмотренно'), ('inQueue', 'В очереди'), ('rejected', 'Отказанно')], default='inQueue', max_length=13, verbose_name='Статус заявки'),
        ),
    ]
